import { cache } from 'react';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getConfigBySlug } from '@/lib/supabase/wheel-config';
import { slugToTitle, validateSlug } from '@/lib/utils/slug';
import { toTitleCase } from '@/lib/utils/text';
import SharedWheelClient from './SharedWheelClient';

interface PageProps {
  params: Promise<{ slug: string }>;
}

// A shared wheel is immutable once created, so let the CDN/server cache the
// rendered page and re-check the database at most once an hour.
export const revalidate = 3600;

// Both generateMetadata and the page need the config. React's cache() dedupes the
// lookup within a single request so we only hit Supabase once per page view.
// Slugs that can't have been generated by us (wrong charset/length) skip the DB entirely.
const loadConfig = cache(async (slug: string) => {
  if (!validateSlug(slug)) return null;
  return getConfigBySlug(slug);
});

// Generate metadata for SEO
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const config = await loadConfig(slug);

  if (!config) {
    return {
      title: 'Wheel Not Found | iWheeli',
      robots: { index: false, follow: false },
    };
  }

  const title = config.teamName ? toTitleCase(config.teamName) : slugToTitle(slug);
  const description = `Spin the wheel: ${config.names.slice(0, 5).join(', ')}${config.names.length > 5 ? '...' : ''}`;

  return {
    title: `${title} | iWheeli – Random Name Picker Wheel`,
    description,
    openGraph: {
      title: `${title} | iWheeli`,
      description,
      url: `https://iwheeli.com/${slug}`,
      siteName: 'iWheeli',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${title} | iWheeli`,
      description,
    },
    alternates: {
      canonical: `https://iwheeli.com/${slug}`,
    },
  };
}

export default async function SharedWheelPage({ params }: PageProps) {
  const { slug } = await params;
  const config = await loadConfig(slug);

  if (!config) {
    notFound();
  }

  return (
    <SharedWheelClient
      names={config.names}
      teamName={config.teamName}
      inputMethod={config.inputMethod}
      accentColor={config.accentColor ?? null}
    />
  );
}
